services:
  db:
    image: postgres:15
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=log_db

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # สำหรับ API
      - "514:514/udp" # สำหรับ Syslog [cite: 12]
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/log_db
    depends_on:
      - db