services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: log_management
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - [cite_start]"8000:8000"     # สำหรับ HTTP API Ingest [cite: 13]
      - [cite_start]"514:514/udp"   # สำหรับ Syslog Ingest [cite: 12]
    depends_on:
      - db