FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

RUN pip install fastapi uvicorn psycopg2-binary pydantic

COPY . .

EXPOSE 514/udp

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]