FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirement.txt

COPY . .

EXPOSE 514/udp

CMD sh -c "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"